# Generated by Django 5.1 on 2024-08-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0003_alter_prediccion_partido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='escudos/'),
        ),
    ]
