# Generated by Django 5.1 on 2024-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0004_equipo_escudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fecha_liga',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
