# Generated by Django 5.1 on 2024-09-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0005_partido_fecha_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='status',
            field=models.CharField(choices=[('programado', 'Programado'), ('por_comenzar', 'Por comenzar'), ('en_juego', 'En juego'), ('finalizado', 'Finalizado')], default='programado', max_length=20),
        ),
    ]
