# Generated by Django 5.1 on 2024-09-13 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0006_partido_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='status',
            field=models.CharField(choices=[('programado', 'Programado'), ('por_comenzar', 'Por comenzar'), ('en_proceso', 'En proceso'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='programado', max_length=20),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('privacidad', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], max_length=50)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(blank=True, related_name='grupos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
