# Generated by Django 5.1 on 2024-09-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0008_grupo_codigo_invitacion_alter_grupo_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='codigo_invitacion',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
