# Generated by Django 5.1 on 2024-11-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0012_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='siglas',
            field=models.CharField(default='Null', max_length=5),
            preserve_default=False,
        ),
    ]
