# Generated by Django 5.1 on 2024-11-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0013_equipo_siglas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='siglas',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
